### PR TITLE
FIPS compliant hashing algoriths 

### PR DESCRIPTION
**Pull request by Hellman101**
Applying all changes from @gregmcguffey without white space changes and other non-functional changes. Unfortunately I couldn't figure out how to undo @gregmgguffey's whitespace commits so this was the easiest solution.

### CODE REVIEW

**Comment by MiloszKrajewski** [comment]
I did not do anything for a very long time as I'm working with .NET core most of the time now, and making it work in .NET core would be a massive task (no AppDomain's anymore). 
I will take a look at this one as it seems to be popular request.
Jst wondering if this method can be implemented just once (seems like 3 times is a lot, for relatively complex function).

**Comment by Hellman101** [comment]
I'll take a quick look. I literally just moved @gregmcguffey's code after I found his was more robust than my earlier solution but all the whitespace changes was a PITA. Give me a couple.

**Comment by Hellman101** [comment]
@MiloszKrajewski Take a look at the updated PR. Moved the logic out into a common location to be referenced.

**Comment by JSlater743** [comment]
Can this be completed?

**Pull request closed without merging**
